CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE auth_personnel (
    admin_uid integer GENERATED BY DEFAULT AS IDENTITY,
    personnel_id character varying(50) NOT NULL,
    passcode_hash character varying(255) NOT NULL,
    full_name character varying(150) NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    last_login timestamp with time zone,
    CONSTRAINT "PK_auth_personnel" PRIMARY KEY (admin_uid)
);

CREATE TABLE sensor_registry (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    sensor_code character varying(50) NOT NULL,
    display_name character varying(100) NOT NULL,
    barangay character varying(100) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL,
    baseline_temp integer NOT NULL DEFAULT 30,
    environment_type character varying(50) NOT NULL DEFAULT 'Unknown',
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_at timestamp with time zone,
    CONSTRAINT "PK_sensor_registry" PRIMARY KEY (id)
);

CREATE TABLE subscribers (
    chat_id bigint NOT NULL,
    username character varying(100) NOT NULL,
    is_subscribed boolean NOT NULL DEFAULT TRUE,
    subscribed_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    last_notified_at timestamp with time zone,
    CONSTRAINT "PK_subscribers" PRIMARY KEY (chat_id)
);

CREATE TABLE heat_logs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    sensor_id integer NOT NULL,
    recorded_temp integer NOT NULL,
    heat_index integer NOT NULL,
    recorded_at timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_heat_logs" PRIMARY KEY (id),
    CONSTRAINT fk_heat_logs_sensor FOREIGN KEY (sensor_id) REFERENCES sensor_registry (id) ON DELETE CASCADE
);

CREATE INDEX idx_auth_personnel_is_active ON auth_personnel (is_active);

CREATE UNIQUE INDEX idx_auth_personnel_personnel_id ON auth_personnel (personnel_id);

CREATE INDEX idx_heat_logs_heat_index ON heat_logs (heat_index);

CREATE INDEX idx_heat_logs_recorded_at ON heat_logs (recorded_at DESC);

CREATE INDEX idx_heat_logs_sensor_id ON heat_logs (sensor_id);

CREATE INDEX idx_sensor_registry_barangay ON sensor_registry (barangay);

CREATE INDEX idx_sensor_registry_is_active ON sensor_registry (is_active);

CREATE UNIQUE INDEX idx_sensor_registry_sensor_code ON sensor_registry (sensor_code);

CREATE INDEX idx_subscribers_is_subscribed ON subscribers (is_subscribed);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260415112753_InitialCreate', '10.0.6');

COMMIT;

