// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefactorHeatAlertPostGre.Data;

#nullable disable

namespace RefactorHeatAlertPostGre.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724040911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("RefactorHeatAlertPostGre.Models.Entities.AdminUser", b =>
                {
                    b.Property<int>("AdminUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("admin_uid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login");

                    b.Property<string>("PasscodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("passcode_hash");

                    b.Property<string>("PersonnelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("personnel_id");

                    b.HasKey("AdminUID");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_auth_personnel_is_active");

                    b.HasIndex("PersonnelId")
                        .IsUnique()
                        .HasDatabaseName("idx_auth_personnel_personnel_id");

                    b.ToTable("auth_personnel", (string)null);
                });

            modelBuilder.Entity("RefactorHeatAlertPostGre.Models.Entities.HeatLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("HeatIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("heat_index");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RecordedTemp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("recorded_temp");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sensor_id");

                    b.HasKey("Id");

                    b.HasIndex("HeatIndex")
                        .HasDatabaseName("idx_heat_logs_heat_index");

                    b.HasIndex("RecordedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_heat_logs_recorded_at");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("idx_heat_logs_sensor_id");

                    b.ToTable("heat_logs", (string)null);
                });

            modelBuilder.Entity("RefactorHeatAlertPostGre.Models.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("barangay");

                    b.Property<int>("BaselineTemp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30)
                        .HasColumnName("baseline_temp");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("EnvironmentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("environment_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("SensorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("sensor_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Barangay")
                        .HasDatabaseName("idx_sensor_registry_barangay");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_sensor_registry_is_active");

                    b.HasIndex("SensorCode")
                        .IsUnique()
                        .HasDatabaseName("idx_sensor_registry_sensor_code");

                    b.ToTable("sensor_registry", (string)null);
                });

            modelBuilder.Entity("RefactorHeatAlertPostGre.Models.Entities.Subscriber", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("chat_id");

                    b.Property<bool>("IsSubscribed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_subscribed");

                    b.Property<DateTime?>("LastNotifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_notified_at");

                    b.Property<DateTime>("SubscribedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("subscribed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("ChatId");

                    b.HasIndex("IsSubscribed")
                        .HasDatabaseName("idx_subscribers_is_subscribed");

                    b.ToTable("subscribers", (string)null);
                });

            modelBuilder.Entity("RefactorHeatAlertPostGre.Models.Entities.HeatLog", b =>
                {
                    b.HasOne("RefactorHeatAlertPostGre.Models.Entities.Sensor", "Sensor")
                        .WithMany("HeatLogs")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_heat_logs_sensor");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("RefactorHeatAlertPostGre.Models.Entities.Sensor", b =>
                {
                    b.Navigation("HeatLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
